### ISSUE TITLE
How to get HTTP request parameters

### ISSUE THREAD

**Issue by OlexandrStepanov** [jthomas/OpenWhiskAction#2]
Hello @jthomas,

Perhaps it's not related to this particular package, but taking into account lack of documentation about OpenWhisk actions on Swift, I would rather ask this question here:

1. How to read HTTP request parameters inside action? I mean HTTP method (GET or POST), headers, body.
2. How to change HTTP response code of action?

**Comment by jthomas** [comment]
👋 @OlexandrStepanov.

Are you invoking the action as a [normal action](https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md#creating-and-invoking-an-action) or a [web action](https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md)?

**Comment by OlexandrStepanov** [comment]
As a normal action, I believe. I'm using this package + Serverless framework.
It must be in some environment variables, like "WHISK_INPUT" used in epilogue.swift. Isn't it?

**Comment by jthomas** [comment]
Can I ask what you are trying to achieve and it'll help me advise you on the best solution? 

Let me give you some background....

## normal actions

[Normal actions](https://github.com/apache/incubator-openwhisk/blob/master/docs/actions.md#creating-swift-actions) don't have access to the HTTP request parameters. They are abstracted away from the HTTP interface used by the runtime container. Functions are called with event parameters (the dictionary string:any) and can return results parameters (dict string:any). They are invoked through the platform API, which sends an internal request in the platform to trigger the invocation. It is being triggered by an internal HTTP request in the platform but from the developer point of view, you are just a function getting called with some parameters.

If you want to have multiple operations, say update the db, read from the db, delete from the db, rather than using HTTP verbs to identify the operation, you deploy separate actions for each operation. Another way would be to pass the operation idenitifer in the event parameters.

## web actions

[Web actions](https://github.com/apache/incubator-openwhisk/blob/master/docs/webactions.md) are a way of publically exposing actions through the platform API. Actions get a unique URL endpoint which can be invoked directly, rather than indireclty through the platform API endpoints. Web actions do have access to the HTTP requests parameters. They can read the HTTP request properties and directly control the HTTP response.

Web actions are just normal actions with a configuration value set.

## api gateway

OpenWhisk has an [API Gateway built-in](https://github.com/apache/incubator-openwhisk/blob/master/docs/apigateway.md) to support creating publically accessible URLs which map HTTP requests (using paths and verbs) to invoke specific actions. The configuration for which action to invoke is handled by the API Gateway, rather than in the action. This uses normal actions, which are oblivious to the fact they are being invoked by the API Gateway. They just get invoked by the service as normal with some event parameters.

## ....but which to use? 😀

It you can give me some context, I can help advise you on the best approach. I can understand it is a bit confusing as first, especially if you are coming from a more traditional app server background.

**Comment by OlexandrStepanov** [comment]
@jthomas Thanks for the detailed explanation. Issue can be closed, cause the root question is clear now.
Here is an tutorial about web actions on Swift:
https://akrabat.com/openwhisk-web-actions/
